### ISSUE TITLE
Remove `dist/` from repo

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick-formatter#7]
> […] the build output in `dist/` […] is currently added to the repo so the package can be used in other projects without it having to be compiled. I think that's something that we should look into […], since it adds a lot of noise.
>
> For comparison, this is how `ky` handles this (it is a package built from TypeScript sources too):
>
> - https://github.com/sindresorhus/ky/blob/v0.28.0/package.json#L13-L28
> - https://github.com/sindresorhus/ky/blob/v0.28.0/.gitignore#L1

— https://github.com/bitcrowd/tickety-tick-formatter/pull/5#discussion_r625722306

**Comment by klappradla** [comment]
All for it 🙇 

I took a brief look at https://github.com/sindresorhus/ky/pull/330 (the PR which moved the library from `.js` to `.ts`). If I understand this correctly, it would require us to have actual `releases` though, which is - in my opinion - the way to go anyways.

**Comment by pmeinhardt** [comment]
> I took a brief look at [sindresorhus/ky#330](https://github.com/sindresorhus/ky/pull/330) (the PR which moved the library from `.js` to `.ts`). If I understand this correctly, it would require us to have actual `releases` though, which is - in my opinion - the way to go anyways.

I think having releases is great, but not a requirement for removing the build artifacts. As far as I could see what's needed are the `build` and/or `prepare` scripts in the `package.json`, so the TypeScript source is compile to JavaScript upon package installation.

**Comment by pmeinhardt** [comment]
Closing since we're deprecating this repo. 👋 See #9
